// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylrzwahzrmmkwmbgwpwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlscnp3YWh6cm1ta3dtYmd3cHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMDEyOTgsImV4cCI6MjA1NTc3NzI5OH0.7tW-ipGUoX8CDltw7VvMTzqvfNbFp6OYChl6rHxxOwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);